### ISSUE TITLE
list does not recognize sub-command FILTER

### ISSUE THREAD

**Issue by ZhiqiangZ** [limbo018/DREAMPlace#1]
When I built the project, the following problems arose:

> CMake Error at dreamplace/ops/dct/CMakeLists.txt:37 (list):
>   list does not recognize sub-command FILTER
> 
> 
> CMake Error at dreamplace/ops/density_overflow/CMakeLists.txt:37 (list):
>   list does not recognize sub-command FILTER
> 
> 
> CMake Error at dreamplace/ops/density_potential/CMakeLists.txt:37 (list):
>   list does not recognize sub-command FILTER
> 
> 
> CMake Error at dreamplace/ops/logsumexp_wirelength/CMakeLists.txt:37 (list):
>   list does not recognize sub-command FILTER
> 
> 
> CMake Error at dreamplace/ops/draw_place/CMakeLists.txt:37 (list):
>   list does not recognize sub-command FILTER
> 
> 
> CMake Error at dreamplace/ops/electric_potential/CMakeLists.txt:37 (list):
>   list does not recognize sub-command FILTER
> 
> 
> CMake Error at dreamplace/ops/greedy_legalize/CMakeLists.txt:32 (list):
>   list does not recognize sub-command FILTER
> 
> 
> CMake Error at dreamplace/ops/hpwl/CMakeLists.txt:37 (list):
>   list does not recognize sub-command FILTER
> 
> 
> CMake Error at dreamplace/ops/move_boundary/CMakeLists.txt:37 (list):
>   list does not recognize sub-command FILTER
> 
> 
> CMake Error at dreamplace/ops/weighted_average_wirelength/CMakeLists.txt:37 (list):
>   list does not recognize sub-command FILTER
> 
> 
> CMake Error at dreamplace/ops/rmst_wl/CMakeLists.txt:32 (list):
>   list does not recognize sub-command FILTER
> 
> 
> CMake Error at dreamplace/ops/place_io/CMakeLists.txt:36 (list):
>   list does not recognize sub-command FILTER

Does this mean that I have some dependencies not installed? Or something else?
How should I solve it?

**Comment by limbo018** [comment]
Hi, the reason comes from the CMake version. Please see the link https://stackoverflow.com/questions/42167432/cmake-list-does-not-recognize-sub-command-filter about this issue. 

The commit [786e3b0](https://github.com/limbo018/DREAMPlace/commit/786e3b0bebc912f30109b7f6615f1f2772dbde86) should have fixed this by setting the required CMake version to 3.13.2. This is the version I used to compile DREAMPlace.
