### ISSUE TITLE
How do I set Dreamplace to run on different GPUs?

### ISSUE THREAD

**Issue by gjhhust** [limbo018/DREAMPlace#117]
When I run dreamplace multi-threading, it will show that CUDA is out of memory. I have four gpus, and I want to be able to run on different gpus. How can I change this

**Comment by limbo018** [comment]
Hi, current DREAMPlace only supports one GPU. You can export ```CUDA_VISIBLE_DEVICES=0``` as the environment variable to set which GPU you'd like to use. 

In general, 8GB GPU memory is enough to handle a million-size design.
