### ISSUE TITLE
error: DefParser::Region has not been declared

### ISSUE THREAD

**Issue by wjx-1999** [limbo018/DREAMPlace#12]
in latest version,I have a problem that error: DefParser::Region has not been declared,how to solve ?
![图片](https://user-images.githubusercontent.com/51050307/71262508-e26d0800-237a-11ea-8365-eff90c882483.png)

**Comment by limbo018** [comment]
> in latest version,I have a problem that error: DefParser::Region has not been declared,how to solve ?
> ![图片](https://user-images.githubusercontent.com/51050307/71262508-e26d0800-237a-11ea-8365-eff90c882483.png)

Hi, have you updated the Limbo submodule with ```git submodule update --recursive``` as well? You can check whether your Limbo version is at commit ec467321410b0904c926d7190d0a327be863e867

Please let me know whether this helps or not. 

Thanks
Yibo

**Comment by wjx-1999** [comment]
![图片](https://user-images.githubusercontent.com/51050307/71266293-151afe80-2383-11ea-9936-9e754d134111.png)
I still have problem

**Comment by limbo018** [comment]
> ![图片](https://user-images.githubusercontent.com/51050307/71266293-151afe80-2383-11ea-9936-9e754d134111.png)
> I still have problem

Could you give more information? I am trying to duplicate your problem. 
1. Is your repo freshly pulled? 
2. Are you using the Docker? 

Thanks

**Comment by limbo018** [comment]
I just tried to compile from a freshly pulled repo in both my local environment and the Docker environment. Unfortunately, I was not able to reproduce the error. Please provide more information about your environment.

**Comment by wjx-1999** [comment]
i don't use the Docker.Because my computer doesn't have a Nvidia graphics card,it doesn't have CUDA. And then, I annotated a passage from CMakeLists.txt
![image](https://user-images.githubusercontent.com/51050307/71307453-a349c000-2429-11ea-928e-45de1106063c.png)
![image](https://user-images.githubusercontent.com/51050307/71307476-f4f24a80-2429-11ea-9537-f28ad0b7f6cd.png)

**Comment by limbo018** [comment]
Could you also provide your gcc version? It is not shown in the screenshot. I can find a machine without CUDA to test. It is expected to work.

**Comment by wjx-1999** [comment]
gcc 5.5 cmake 3.15.4 boost 1.66
![image](https://user-images.githubusercontent.com/51050307/71307600-6da5d680-242b-11ea-999d-8b33933261e7.png)
![image](https://user-images.githubusercontent.com/51050307/71307615-929a4980-242b-11ea-8a1c-78674d153d84.png)

**Comment by limbo018** [comment]
I just tried compiling on a machine without CUDA. It worked fine. I used gcc 5.1, boost 63. I also tried gcc 7.4. I don't think gcc 5.5 will fail. 

Do you mind doing some experiments as follows? 
```
cd thirdparty/Limbo
git status
git log -2
```
I'd like to see the message displayed. 

Thanks
Yibo

**Comment by wjx-1999** [comment]
![image](https://user-images.githubusercontent.com/51050307/71308251-2ae8fc00-2435-11ea-8f31-0701fcc3889a.png)
![image](https://user-images.githubusercontent.com/51050307/71308332-10fbe900-2436-11ea-95a1-6212baf7365e.png)

My python version is 2.7.12, I don't know that's a problem

**Comment by limbo018** [comment]
I just tried compiling with python 2.7 and gcc 5.1. Everything looks fine. Is there any way you can send me your full log? You can send to my email: yibolin at pku.edu.cn

When you run ```make```, please use ```make VERBOSE=1 >& log.txt``` to go to verbose mode and redirect the message to the log file. With more information, I may be able to find some clue. Please remove everything in the build folder and redo the cmake step before you make. 

Thanks
Yibo

**Comment by wjx-1999** [comment]
compile successfully after updating the code
but i encounter another problem when running cmd  'python dreamplace/Placer.py test/ispd2015/lefdef/mgc_des_perf_1.json'

![图片](https://user-images.githubusercontent.com/51050307/71309360-f596db00-2441-11ea-9073-d491d5847434.png)

**Comment by limbo018** [comment]
That's good. I didn't put the benchmarks in the repo, because they are very large. Currently you can try ispd2005 benchmarks, by downloading using the ispd2005.py script. I will prepare similar script for ispd2015 benchmarks soon.

**Comment by wjx-1999** [comment]
I still can't run the ispd05 demo test afetr running cmd 'python dreamplace/Placer.py test/ispd2005/adaptec1.json'
the source file directory as follows benchmarks/ispd2005/adaptec1/adaptec1.aux
![图片](https://user-images.githubusercontent.com/51050307/71309734-81ab0180-2446-11ea-9118-222357ab7c3d.png)
![图片](https://user-images.githubusercontent.com/51050307/71309744-99828580-2446-11ea-8977-f4afb474bf1b.png)

**Comment by limbo018** [comment]
I think you were running from the wrong directory. You need to run from the installation directory, not the repo root directory. 
Suppose you installed DREAMPlace to DREAMPlace/install. Then you need to, 
```
cd install
ls benchmarks # check whether ispd2005 benchmark suites are there
python dreamplace/Placer.py test/ispd2005/adaptec1.aux
```

**Comment by wjx-1999** [comment]
![图片](https://user-images.githubusercontent.com/51050307/71310059-8e315900-244a-11ea-8648-ab0184710411.png)
I still can't run the ispd05 demo test as your instruction

**Comment by limbo018** [comment]
Sorry, I corrected the typo of *.aux to *.json. Meanwhile, as you don't have gpu, please change the gpu parameter in the json file to 0. 
Are you able to open the input files?

**Comment by wjx-1999** [comment]
I can open the input files and set gpu = 0, but can't run

**Comment by limbo018** [comment]
what's the error message?

**Comment by wjx-1999** [comment]
[ERROR  ] unknown option: for
[INFO   ] reading required
Could not open input file required
[ERROR  ] LEF file parsing failed: required
[ASSERT ] /home/wangsf/workspace/DREAMPlace/dreamplace/ops/place_io/src/place_io.cpp:457: DreamPlace::PlaceDB place_io_forward(const pybind11::list&): Assertion `flag' failed: failed to read input LEF files

**Comment by limbo018** [comment]
Hi, I got some luck to reproduce the problem and just fixed it. The problem came from parsing the parameters with default values as string. 

Please pull the latest commit from the master branch. Then, you can go to the build directory and run ```make install``` again. I only changed some python files, so it should be quick. 
After that, you can go to the install directory and test again.

**Comment by wjx-1999** [comment]
Hi,now I can run the ispd2005 demo test successfully,but there is a problem when I run the ispd2015 demo test. 
![image](https://user-images.githubusercontent.com/51050307/71315813-987e4200-24a0-11ea-97fe-1dbaa5e915f7.png)
![image](https://user-images.githubusercontent.com/51050307/71315822-bf3c7880-24a0-11ea-9529-a0f6380a8353.png)

**Comment by limbo018** [comment]
I found the problem came from reading the DEF file with UNPLACED instances which do not specify the ORIENT. The commit [a0d239a](https://github.com/limbo018/DREAMPlace/commit/a0d239a9aef0f51524b38e20ea528fd7db89f7af) has fixed the issue. 

However, it needs to be noted that currently DREAMPlace can only formally support ISPD2015 benchmarks in detailed placement, as routability and fence regions have not been considered in global placement and legalization. The JSON files provided in the repo also set the ```global_place_flag = 0``` and ```legalize_flag = 0```.

**Comment by wjx-1999** [comment]
Thank you !
I will continue to testing and feedback.

**Comment by ArEsKay3** [comment]
> compile successfully after updating the code
> but i encounter another problem when running cmd 'python dreamplace/Placer.py test/ispd2015/lefdef/mgc_des_perf_1.json'
> 
> ![图片](https://user-images.githubusercontent.com/51050307/71309360-f596db00-2441-11ea-9073-d491d5847434.png)

What exactly did you do to fix this? I'm having the same problem.
