### ISSUE TITLE
In 4.0 how to generate flute LUT

### ISSUE THREAD

**Issue by kouyichi** [limbo018/DREAMPlace#142]
in dreamplace/ops/timing/src/timing_cpp.cpp line139-144

`  using Point2i = ::DreamPlace::Point<int>;
  dreamplacePrint(kINFO, "launch rc tree construction...\n");
  flute::readLUT(
      "thirdparty/flute/lut.ICCAD2015/POWV9.dat",
      "thirdparty/flute/lut.ICCAD2015/POST9.dat");
  auto beg = std::chrono::steady_clock::now();
`
flute use a look up table that already made. If I want to use the 4.0 in something out of iccad2015, how can I generate the look up table?

**Comment by enzoleo** [comment]
They come from the source code of `flute`. It should also work in other benchmarks.

**Comment by kouyichi** [comment]
> They come from the source code of `flute`. It should also work in other benchmarks.

Sorry, I'm not very familiar with the flute code. I just saw there is a readLUT and not a writeLUT function; where can I find the function that generates a LUT from some file?

**Comment by limbo018** [comment]
You'd better read the original FLUTE paper to get the idea how it works before looking into the code. Its LUT is quite general and does not requires re-generation for different designs.&nbsp;


https://ieeexplore.ieee.org/document/4358497




                       
Original
                       
                     

From:"kouyichi"< ***@***.*** &gt;;

Date:2023/7/13 1:25

To:"limbo018/DREAMPlace"< ***@***.*** &gt;;

CC:"Subscribed"< ***@***.*** &gt;;

Subject:Re: [limbo018/DREAMPlace] In 4.0 how to generate flute LUT (Issue#142)




  
They come from the source code of flute. It should also work in other benchmarks.
  
Sorry, I'm not very familiar with the flute code. I just saw there is a readLUT and not a writeLUT function; where can I find the function that generates a LUT from some file?
