### ISSUE TITLE
Have no "flute.h" when make install

### ISSUE THREAD

**Issue by LmMax0** [limbo018/DREAMPlace#144]
![图片](https://github.com/limbo018/DREAMPlace/assets/60802095/8ab2e639-9f81-4753-b076-fece18a3aebf)

I have uncommented the line of code `add_subdirectory(rmst_wl)`.

However, during the subsequent construction process, there were issues as shown in the above images. I have tried many methods myself, but none of them have been effective. I'm sorry, because I have a lack of knowledge in cmake.

I would like to ask how I can solve this problem, as this module of DREAMPlace has been referenced in other open source projects, so I cannot avoid this problem.

Thank you for your guidance！

**Comment by limbo018** [comment]
Compile problem fixed in https://github.com/limbo018/DREAMPlace/commit/477ea7a0b4e479c8bfe425e9499946c6bfd5525b

You can try the `develop` branch.

**Comment by LmMax0** [comment]
It works. Amazing!
Thank you very much!
