### ISSUE TITLE
How to compile DREAMPlace into a library and integrate it into our project

### ISSUE THREAD

**Issue by Yixin-Gong** [limbo018/DREAMPlace#147]
Hello, Mr. Lin, how to compile DREAMPlace into a library so that our programs can call it, do you have any good solutions?

**Comment by limbo018** [comment]
Probably you want to check out something like Pyinstaller or its alternatives.

**Comment by Yixin-Gong** [comment]
> Probably you want to check out something like Pyinstaller or its alternatives. 

Thanks!
