### ISSUE TITLE
run without gpu

### ISSUE THREAD

**Issue by mavoyang** [limbo018/DREAMPlace#153]
How can I configure CMAKE to make Dreamplacer run without GPU???

To work with other projects, I need to build version 2.2.0 of Dreamplacer. 
I first built the Docker container, and I can find Cuda 10.0 in it.
Then, if I run the Docker container with GPU, I can successfully 'make'. But running any benchmark with 'placer.py' gets stuck at '[INFO] DREAMPlace - move cells to the center of the layout with random noise.'
![截屏2023-10-17 10 40 06](https://github.com/limbo018/DREAMPlace/assets/45881119/d14beed6-6af8-457f-8fb2-9bd8d1cad6cb)

This may be due to the incompatibility between the old version of Dreamplacer and the current CUDA.
So, I tried running the Docker container without GPU, but running any benchmark with 'placer.py' results in an error 'Found no NVIDIA driver on your system' after 'move cells to the center of the layout with random noise.'
![截屏2023-10-17 11 17 34](https://github.com/limbo018/DREAMPlace/assets/45881119/5bf1ac98-7324-44e0-9443-6f1260df96bf)

How should I configure CMake to build a Dreamplacer that doesn't use CUDA at all?" Or how can I fix it to run with Cuda?

One more thing, for the newest Dreamplacer, it runs with GPU well when I use the provided docker.

**Comment by limbo018** [comment]
You can modify the ```gpu``` parameter in the ```JSON``` input file to 0 for CPU.

**Comment by mavoyang** [comment]
Ha, it's really a rookie question. Thanks!
