### ISSUE TITLE
docker run bug?

### ISSUE THREAD

**Issue by jzh800** [limbo018/DREAMPlace#17]
docker run -it -v $(pwd):/DREAMPlace limbo018/dreamplace:cuda bash
C:\Program Files\Docker\Docker\resources\bin\docker.exe: invalid reference format: repository name must be lowercase.
See 'C:\Program Files\Docker\Docker\resources\bin\docker.exe run --help'.

 docker run -it -v $(pwd):/dreamlace limbo018/dreamplace:cuda bash
C:\Program Files\Docker\Docker\resources\bin\docker.exe: invalid reference format.
See 'C:\Program Files\Docker\Docker\resources\bin\docker.exe run --help'.

using this command could go into bash shell.
docker run -it -v /dreamlace limbo018/dreamplace:cuda bash

win10 docker hub

**Comment by limbo018** [comment]
Do you have a space in your repo name? Can you try change "dreamlace limbo018" to "dreamplace_limbo018"?

**Comment by jzh800** [comment]
docker run -it -v dreamplace_limbo018/dreamplace:cuda bash
C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: invalid volume specification: 'dreamplace_limbo018/dreamplace:cuda': invalid mount config for type "volume": invalid mount path: 'cuda' mount path must be absolute.
See 'C:\Program Files\Docker\Docker\resources\bin\docker.exe run --help'.

**Comment by limbo018** [comment]
Sorry for the misunderstanding about your command line code. Your original command with a space should be correct. 

If I understand correctly, you suggest the following command and it works under windows. 
docker run -it -v /dreamplace limbo018/dreamplace:cuda bash

That's possible, because I only tested under linux and $(pwd) is not necessary.

**Comment by jzh800** [comment]
docker run -it -v /dreamplace limbo018/dreamplace:cuda bash

using this command could go into bash shell.

**Comment by jzh800** [comment]
merge in
