### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by IshraqAtUCF** [limbo018/DREAMPlace#170]
For the current commit `d510848` it is giving me an error while building. 

<img width="1545" alt="image" src="https://github.com/limbo018/DREAMPlace/assets/156346459/0db3b95c-3275-4f88-87f1-6d586a757190">

Just to reiterate my building process:

I initialized the submodules and directly tried to build without docker. 

It completes the cmake but gives error while I try to `make`.

**Comment by limbo018** [comment]
What's your gcc/g++ version?

**Comment by limbo018** [comment]
Btw, you can skip OpenTimer's unittest, as it is not used.

**Comment by IshraqAtUCF** [comment]
It is 11.4

<img width="657" alt="image" src="https://github.com/limbo018/DREAMPlace/assets/156346459/ebdc5a5d-754f-4745-802b-db6cb990e478">


Also, how to skip the OpenTimer's unittest?

**Comment by IshraqAtUCF** [comment]
Is this because of higher version of gcc/g++? @limbo018
