### ISSUE TITLE
Node Initial Position Influence in DREAMPlace

### ISSUE THREAD

**Issue by master-alileo** [limbo018/DREAMPlace#202]
In DREAMPlace, are there any parameters that can enhance the influence of my node's initial position in subsequent layouts (i.e., I would like to avoid significant deviation from the initial position in the subsequent layouts)?

**Comment by limbo018** [comment]
You can set ```random_center_init_flag``` to 0, to disable random initialization.

**Comment by master-alileo** [comment]
Apart from the `random_center_init_flag` parameter, are there any other parameters in DREAMPlace that can influence the impact of the initial position on subsequent layouts? @limbo018

**Comment by limbo018** [comment]
I am not aware of anything else.

**Comment by master-alileo** [comment]
Thank you for your response.
