### ISSUE TITLE
read file error

### ISSUE THREAD

**Issue by JZP1112** [limbo018/DREAMPlace#203]
Hello, author. I try to put the output of DreamPlace in NCTUgr to obtain results but failed. How can I solve the problem

run ./NCTUgr ICCAD /home/Applications/benchmarks/ispd2005/adaptec2/adaptec2.aux adaptec2.lg.pl ICCAD12.set resluts

read /home/Applications/benchmarks/ispd2005/adaptec2/adaptec2.nodes
read /home/Applications/benchmarks/ispd2005/adaptec2/
terminate called after throwing an instance of 'std::ios_base::failure'
what(): basic_filebuf::underflow error reading the file
Aborted (core dumped)

**Comment by limbo018** [comment]
You cannot run ispd2005 benchmarks with NCTUgr, because these benchmarks do not provide routing information. NCTUgr only supports DAC2012 and ICCAD2012 benchmarks. You can have a try.
