### ISSUE TITLE
Bookshelf file parsing failed: benchmarks/ispd2005/adaptec1/adaptec1.aux

### ISSUE THREAD

**Issue by jeshu54** [limbo018/DREAMPlace#23]
Hi @limbo018 

When I am running the below code.
![Screen Shot 2020-06-03 at 9 19 01 PM](https://user-images.githubusercontent.com/60354888/83704342-de0e7180-a5df-11ea-9f26-7c98e879b726.png)

I am getting below error.

![Screen Shot 2020-06-03 at 8 55 11 PM](https://user-images.githubusercontent.com/60354888/83704353-e4045280-a5df-11ea-92d4-d1603a8b2547.png)

I have re downloaded the benchmark files but still getting this error.

Could you please let me know what the error is?

**Comment by limbo018** [comment]
What's the path of your benchmark? Is it under install/benchmarks/ispd2005?

**Comment by jeshu54** [comment]
@limbo018 The files got uncompressed to the root directory's benchmark folder not the install's benchmark folder. Should I copy the uncompressed files from root's benchmark to install's benchmark?

**Comment by jeshu54** [comment]
@limbo018 I think I will be able to solve it. I was uncompressing data from root directory not install.

Thank you for the assistance. This is my first time building something like this.

**Comment by limbo018** [comment]
Yes, the benchmarks should be under install/benchmarks. You may check out the aux_input path in the JSON file.
