### ISSUE TITLE
Instructions up to date?

### ISSUE THREAD

**Issue by harismeharis** [limbo018/DREAMPlace#26]
Hi,

Really interesting approach and well written paper. However I am trying to follow closely the instructions to run the benchmarks (python dreamplace/Placer.py test/ispd2005/adaptec1.json) and it is not working. Are the instructions up to date?

**Comment by harismeharis** [comment]
To be more specific, I am running : 
 python dreamplace/Placer.py test/ispd2005/adaptec1.json
and I get : 
Traceback (most recent call last):
  File "dreamplace/Placer.py", line 19, in <module>
    import dreamplace.configure as configure
ModuleNotFoundError: No module named 'dreamplace.configure'

**Comment by limbo018** [comment]
Please make sure you execute the commands in the *install* directory, not the repo directory.

**Comment by harismeharis** [comment]
Thank you
