### ISSUE TITLE
How do I read a netlist with gates which have multiple output pins?

### ISSUE THREAD

**Issue by PeiyanFlying** [limbo018/DREAMPlace#37]
Hi, I meet with some trouble when I read my own netlist.
This is my own device, a two output spliter. And here is the cell.lef of the spliter2. How ever I meet with this trouble when I run the Global Placement part. Beg your help! Many thanks!

<img width="188" alt="Screen Shot 2021-04-28 at 2 22 15 AM" src="https://user-images.githubusercontent.com/45463777/116356203-f9223b00-a7c8-11eb-9dbc-fe27e228cecc.png">
<img width="296" alt="Screen Shot 2021-04-28 at 2 25 54 AM" src="https://user-images.githubusercontent.com/45463777/116356381-3090e780-a7c9-11eb-9bce-428ed3766b71.png">
<img width="847" alt="Screen Shot 2021-04-28 at 2 26 43 AM" src="https://user-images.githubusercontent.com/45463777/116356408-38508c00-a7c9-11eb-9ce1-eb837f2b0420.png">

**Comment by limbo018** [comment]
According to the error message, I think you need to check the macro named "add_bb" in your LEF file. It complains failed to find a pin named "o".

**Comment by PeiyanFlying** [comment]
Thank you for your timely reply. And as you see, there is no pin "o" in the macro "add_bb" defined in my LEF file. 
<img width="334" alt="Screen Shot 2021-04-28 at 1 32 50 PM" src="https://user-images.githubusercontent.com/45463777/116448070-b3945b00-a826-11eb-80f0-4421c551520f.png">

**Comment by PeiyanFlying** [comment]
And is it a problem in "after_legalized.ntup.fix.def" ? I just use a file from other designs in ispd2015. Because we only need the Global Placement process.
Thanks!

**Comment by PeiyanFlying** [comment]
And this is how my netlist look like. Maybe I use the different datatype? (wire, not input?)
<img width="334" alt="Screen Shot 2021-04-28 at 4 55 16 PM" src="https://user-images.githubusercontent.com/45463777/116471536-cb79d800-a842-11eb-98a7-28f73ec5adca.png">
<img width="334" alt="Screen Shot 2021-04-28 at 4 55 34 PM" src="https://user-images.githubusercontent.com/45463777/116471548-cf0d5f00-a842-11eb-9bfe-415389db99a1.png">

**Comment by limbo018** [comment]
Looks like you have solved your previous problem. 

For the wire type (wire or input/output), the declaration of input/output should match ```adder (a, b, c, cout, s)```. Other signals should be ```wire```.

**Comment by PeiyanFlying** [comment]
Yes! Many thanks for your detail reply.
