### ISSUE TITLE
Typo in CMakeLists.txt

### ISSUE THREAD

**Issue by ArEsKay3** [limbo018/DREAMPlace#5]
https://github.com/limbo018/DREAMPlace/blob/e35831b070107b305762004ae7e4f5b4562b67e7/CMakeLists.txt#L33

**Comment by limbo018** [comment]
> https://github.com/limbo018/DREAMPlace/blob/e35831b070107b305762004ae7e4f5b4562b67e7/CMakeLists.txt#L33

Hi, the latest [commit](https://github.com/limbo018/DREAMPlace/commit/a88fc8254f0db68f218831ce1ae8e025746660b0) has fixed this issue.
