### ISSUE TITLE
How to place the DAC-2012 benchmark suite

### ISSUE THREAD

**Issue by KaitoKiddo** [limbo018/DREAMPlace#54]
Hi, I'm sorry to bother. I could place the ispd2005 benchmark suite, but when I tried to place DAC-2012 benchmark suite I met some problems.

I added dac-2012 benchmark suite in ./benchmarks, then I run the cmd "python dreamplace/Placer.py test/dac2012/superblue2.json".

It could place the superblue2 benchmark and generated the .pl file "superblue2.NCTUgr.pl". 

But when reading the NCTU-GR 2.0, it threw an error: 
FileNotFoundError: [Errno 2] No such file or directory: '...../results/superblue2/superblue2.NCTUgr.ofinfo'.
Why is there no such file in ./results ?

**Comment by limbo018** [comment]
> Hi, I'm sorry to bother. I could place the ispd2005 benchmark suite, but when I tried to place DAC-2012 benchmark suite I met some problems.
> 
> I added dac-2012 benchmark suite in ./benchmarks, then I run the cmd "python dreamplace/Placer.py test/dac2012/superblue2.json".
> 
> It could place the superblue2 benchmark and generated the .pl file "superblue2.NCTUgr.pl".
> 
> But when reading the NCTU-GR 2.0, it threw an error: FileNotFoundError: [Errno 2] No such file or directory: '...../results/superblue2/superblue2.NCTUgr.ofinfo'. Why is there no such file in ./results ?

Hi, I just tried running superblue2 in DAC 2012 benchmarks. It works fine on my side. The *.ofinfo file is generated by NCTUgr under results/superblue2/ of your install directory. 

Could you check if NCTUgr crashed on your machine?

Thanks

**Comment by KaitoKiddo** [comment]
Thank you for your reply. 
In thirdparty, the NCTUgr.ICCAD2012 folder contains NCTUgr, DAC12.set, ICCAD12.set files, etc.
Does the NCTUgr need to be downloaded from DAC2012 contest or can be deployed to my machine when cmake?

**Comment by limbo018** [comment]
You can use the NCTUgr binary in the folder. I doubt the binary probably crashed when running on your machine. I actually downloaded the binary from the contest website.

**Comment by Eternity666** [comment]
Hi, sorry to bother! I met the same problem as you. Have you solved it?

**Comment by limbo018** [comment]
Not sure if this can help. My machine is ubuntu 18.04 LTS with NVIDIA 2080TI GPU. You'd better make sure NCTUgr does not crash on standalone runs, as DREAMPlace will call the NCTUgr binary during the optimization.

**Comment by Eternity666** [comment]
Running NCTUgr will result in a segmentation fault. When I view the core file through GDB, this information will be displayed. Do you know how to solve it? Thank you!

![9e88fd9f16d9f20b3cf64bbdb49ce16](https://user-images.githubusercontent.com/46997815/158774461-c6354fc6-e076-4090-a026-9c22ea6061a6.png)

**Comment by limbo018** [comment]
It looks like the binary does not fit your machine. NCTUgr is not open-source, so unfortunately I don't know how it was written either.

**Comment by gjhhust** [comment]
> Running NCTUgr will result in a segmentation fault. When I view the core file through GDB, this information will be displayed. Do you know how to solve it? Thank you!
> 
> ![9e88fd9f16d9f20b3cf64bbdb49ce16](https://user-images.githubusercontent.com/46997815/158774461-c6354fc6-e076-4090-a026-9c22ea6061a6.png)

I also have same error，Did you solve?

**Comment by gjhhust** [comment]
> > > Hi, I'm sorry to bother. I could place the ispd2005 benchmark suite, but when I tried to place DAC-2012 benchmark suite I met some problems.
> > > I added dac-2012 benchmark suite in ./benchmarks, then I run the cmd "python dreamplace/Placer.py test/dac2012/superblue2.json".
> > > It could place the superblue2 benchmark and generated the .pl file "superblue2.NCTUgr.pl".
> > > But when reading the NCTU-GR 2.0, it threw an error: FileNotFoundError: [Errno 2] No such file or directory: '...../results/superblue2/superblue2.NCTUgr.ofinfo'. Why is there no such file in ./results ?
> > 
> > 
> > Hi, I just tried running superblue2 in DAC 2012 benchmarks. It works fine on my side. The *.ofinfo file is generated by NCTUgr under results/superblue2/ of your install directory.
> > Could you check if NCTUgr crashed on your machine?
> > Thanks
> 
> Thank you for your reply. In thirdparty, the NCTUgr.ICCAD2012 folder contains NCTUgr, DAC12.set, ICCAD12.set files, etc. Does the NCTUgr need to be downloaded from DAC2012 contest or can be deployed to my machine when cmake?

I'm sorry to bother you, but did you solve it? I had the same problem

**Comment by ZhuLinsen** [comment]
@KaitoKiddo @Eternity666  @gjhhust hello, I'm sorry to bother you, but did you solve it? I had the same problem. 
I'm puzzled as to why it is throwing errors because I am running it in a Docker environment.

Any suggestions would be greatly appreciated.Thank you.

**Comment by KaitoKiddo** [comment]
I have finished placing dac2012 benchmark suite, without error. But I'm sorry that I don't run it in docker. @gjhhust @ZhuLinsen

**Comment by gjhhust** [comment]
> 

I was using superblue1 to run fast and default, but there was no problem with dac2012 benchmark. To see if NCTUGR is the problem, try NCTUGR on its own: https://[people.cs.nctu.edu.tw/~whliu/NCTU-GR.htm](https://people.cs.nctu.edu.tw/~whliu/NCTU-GR.htm)

**Comment by gjhhust** [comment]
> I have finished placing dac2012 benchmark suite, without error. But I'm sorry that I don't run it in docker. @gjhhust @ZhuLinsen

Sorry, I used to run in my environment, and this issue has my environment description: https://github.com/limbo018/DREAMPlace/issues/113

**Comment by KaitoKiddo** [comment]
I have never met the errors that you mentioned. In DREAMPlace it has the NCTUgr and will be run when placing dac2012 benchmark. Maybe you can check your environment or docker. Thank you for your attention to this issue. Closing it.

**Comment by ZhuLinsen** [comment]
> 
Hi @KaitoKiddo @gjhhust, Thank you for your response, so how did you solve the error as below？
`FileNotFoundError: [Errno 2] No such file or directory: '...../results/superblue2/superblue2.NCTUgr.ofinfo'.
Why is there no such file in ./results ?`

**Comment by KaitoKiddo** [comment]
Maybe you need to check your NCTUgr that is working.

**Comment by xiaoqiang88888** [comment]
@KaitoKiddo @limbo018 @ZhuLinsen @Eternity666 @gjhhust Respected teachers, I sincerely apologize for the interruption. Could you please advise on how to resolve this issue? I have tried many times, but the NCTUgr keeps being broken.

![Image](https://github.com/user-attachments/assets/fa74eece-88af-4fff-8b6b-f332c4705cff)

**Comment by KaitoKiddo** [comment]
Hi, you should check to see how the NCTUgr tool works I think, and this is not a problem within DREAMPlace.

**Comment by xiaoqiang88888** [comment]
@KaitoKiddo 老师您好，我觉得我的NCTUgr应该是work的如下图所示，能正常的routing，也生成相应的文件，但是唯独没有生成ofinfo文件，方便加您一个联系方式么，如果能解决将不胜感激 qq：903497079

![Image](https://github.com/user-attachments/assets/8e8d7167-2c4f-43bc-a3ef-51155454e0a4)

![Image](https://github.com/user-attachments/assets/8522beac-c39b-48e8-86cd-6c78f7be1a4f)
