### ISSUE TITLE
when container runs /DREAMPlace cannot be found

### ISSUE THREAD

**Issue by YuanGao19** [limbo018/DREAMPlace#55]
hello and sorry to bother. The dreamplace dir is empty. wondering how to solve this...
![image](https://user-images.githubusercontent.com/75833395/146904163-4a065afa-55f3-4e9c-8dc5-c59a5d9b4761.png)

**Comment by YuanGao19** [comment]
wow I just switched to wsl and the DREAMPlace dir is normal(with files and not empty at all). It seems like the problem I mentioned above just happens to Windows user...?

**Comment by limbo018** [comment]
Hi, the project has only been tested under Linux.

**Comment by YuanGao19** [comment]
OK thanks! Great work!
