### ISSUE TITLE
Build with docker issue

### ISSUE THREAD

**Issue by HAOHANZHOU** [limbo018/DREAMPlace#59]
![issue](https://user-images.githubusercontent.com/54381714/148873587-9ea00aaf-dabb-45cd-8318-d55c7d4e7420.png)
Hi, I am not familiar with docker, so I just follow "How to Build". 
I choose to Build with docker->Option one->Run without GPU on Windows
But when it comes to step 6: I found there is no directory named DREAMPlace
I was wondering if I missed anything.
Thanks.

**Comment by limbo018** [comment]
Docker only provides you the environment for building. You still need to clone and build/install the code following the instructions.
