### ISSUE TITLE
Issue on making: nvcc fatal   : Unsupported gpu architecture 'compute_86'

### ISSUE THREAD

**Issue by Dinple** [limbo018/DREAMPlace#60]
Hi all,

I got DREAMPlace running successfully on my computer using the CPU version. However, when trying to make using the nvidia docker, I kept on getting the error saying nvcc fatal   : Unsupported gpu architecture 'compute_86'.

The error is shown below:
![Screenshot from 2022-01-12 16-46-12](https://user-images.githubusercontent.com/24643892/149246175-96d50686-142b-4495-8f1f-8305be1a0c9d.png)

I followed the installation guide from the nvidia docker repository and even tested the installation. Here is nvidia-smi and nvcc -V inside docker container:
![Screenshot from 2022-01-12 16-51-15](https://user-images.githubusercontent.com/24643892/149246336-455b1200-f659-4b33-a3f1-53803baf8adb.png)
![Screenshot from 2022-01-12 16-51-41](https://user-images.githubusercontent.com/24643892/149246342-dedaffca-f02a-4b7a-ae10-8b66de2b9868.png)

Since the original system I was using is built on a 3090, after I did some search online, some suggested a compatibility issue with cuda 11 and 30-series card. However, after redoing the whole installation on a gtx 1080 with cuda 11, same issue occurs again. 

I am not really sure if there is a solution to this issue but if anyone is running DREAMPlace on a GPU, could you let me know which CUDA version and GPU you are using?

**Comment by limbo018** [comment]
Hi, if you switch to GTX 1080, compute_86 does not work. You need to check the list and set the correct architecture compatibility (it is mentioned in the README). 

https://developer.nvidia.com/cuda-gpus

Thanks

**Comment by Dinple** [comment]
Hi, thanks for the info. I eventually solved the issue by simply change the pytorch version to 1.9.0 and cuda version >= 11.1 in the dockerfile and rebuild the container.
