### ISSUE TITLE
Bookshelf file parsing failed

### ISSUE THREAD

**Issue by Eternity666** [limbo018/DREAMPlace#68]
Sorry to bother. When I run ```python ./dreamplace/Placer.py test/dac2012/superblue2.json``` in the install_path, an error occured. 
![image](https://user-images.githubusercontent.com/46997815/160265593-fe3b4355-4d1e-4e8b-818f-6a14d2653e0a.png)

Would you please advise how to solve it? Thank you!

**Comment by limbo018** [comment]
It looks like DAC 2012 benchmarks are missing. Have you downloaded them and put in the correct locations as the json file defined?

**Comment by Eternity666** [comment]
Thanks for your reply! I solved this problem！

**Comment by PKUTAN** [comment]
> Thanks for your reply! I solved this problem！

How did you solve it exactly?

**Comment by Eternity666** [comment]
Just put the benchmark data in the correct path. Alternatively, you can modify the path to the correct path of the .aux file in corresponding json file.

**Comment by PKUTAN** [comment]
> Just put the benchmark data in the correct path. Alternatively, you can modify the path to the correct path of the .aux file in corresponding json file.

That's wield for my case, I have put the file in the correct path, however the error still occur.
