### ISSUE TITLE
Save intermediate placements

### ISSUE THREAD

**Issue by choltz95** [limbo018/DREAMPlace#9]
Hi, I am interested in recovering intermediate placement positions during global placement. 
I save the initial PlaceDB & I try to get cell placements by accessing parameters in NonLinearPlace model: 
`cur_pos = model.data_collections.pos[0].data.clone().cpu().numpy()
   placement_hist.append(cur_pos)`

When I recover placement_hist after global placement, all positions are 459, but the .pl output yields reasonable placements:
`numpy.nan_to_num(numpy.unique(placement_hist[100])).sum()
   459.0`

Additionally, when I set the plot flag, the first plot looks okay, but I can't open any subsequent plots.

Do you have any recommendation for what I'm trying to do? Thanks.

**Comment by ZixuanJiang** [comment]
Many thanks for your feedback. Unfortunately, we cannot reproduce your issue on our end. Could you offer us more details? The results of _bigblue1_ benchmark are shown below for your information.

The expression of `np.nan_to_num(np.unique(cur_pos)).sum()` is non-stationary across iterations. The figures below show the plots of the global placement.

- 0th iteration. The sum is 4656757760.
![iter0000](https://user-images.githubusercontent.com/34562278/65560037-b4eefa80-df02-11e9-8b9f-e46474734822.png)

- 100th iteration. The sum is 7133514240.
![iter0100](https://user-images.githubusercontent.com/34562278/65560042-bc160880-df02-11e9-8562-ae043f0e195f.png)

- 200th iteration. The sum is 7278047744.
![iter0200](https://user-images.githubusercontent.com/34562278/65560046-be786280-df02-11e9-82d6-fe03829fdda3.png)

- 300th iteration. The sum is 7060523520.
![iter0300](https://user-images.githubusercontent.com/34562278/65560047-c0422600-df02-11e9-9949-21c24c933c84.png)

- 400th iteration. The sum is 6763920896.
![iter0400](https://user-images.githubusercontent.com/34562278/65560050-c2a48000-df02-11e9-96c3-fe72c98a04d2.png)

- 500th iteration. The sum is 6733430272.
![iter0500](https://user-images.githubusercontent.com/34562278/65560054-c46e4380-df02-11e9-9703-7534681177e3.png)

- 600th iteration. The sum is 6738869248.
![iter0600](https://user-images.githubusercontent.com/34562278/65560057-c59f7080-df02-11e9-8f99-6428ea3152f8.png)

- 676th iteration
![iter0676](https://user-images.githubusercontent.com/34562278/65560060-c801ca80-df02-11e9-8355-8eeab083f366.png)

**Comment by choltz95** [comment]
Hi, thank you very much for your detailed response. - I have found the reasons for my issues.

I don't have a GPU machine at the moment. I am running in a Google colab environment w/ Tesla K80 (compute capability ~3.7).

The reason for the issues is that K80 does not satisfy compute capability requirement described in the README, and build fails if I reduce the cuda cc parameter. 

I am able to recover intermediate placements by running placement on the CPU.

**Comment by limbo018** [comment]
> Hi, thank you very much for your detailed response - I have found the reasons for my issues.
> 
> I don't have a GPU machine at the moment. I am running in a Google colab environment w/ Tesla K80 (compute capability ~3.7).
> 
> I guess the reason for the issues is that K80 does not satisfy compute capability requirement described in the README, and build fails if I reduce the cmake cuda cc parameter to 30.
> 
> I am able to recover intermediate placements by running placement on the CPU.
> 
> Also, FYI it looks like PlaceDB object is missing the read_pl function which is called at the end of placement.

Yes, compute compatibility 60 or higher is required for GPU. 

Btw, could you print the error message on the missing read_pl function you mentioned? 

Thanks

**Comment by choltz95** [comment]
`Traceback (most recent call last):
  File "dreamplace/Placer.py", line 102, in <module>
    place(params)
  File "dreamplace/Placer.py", line 68, in place
    placedb.read_pl(dp_out_file+".ntup.pl")
AttributeError: 'PlaceDB' object has no attribute 'read_pl'`

**Comment by limbo018** [comment]
> ```
> Traceback (most recent call last):
> File "dreamplace/Placer.py", line 102, in <module>
>     place(params)
> File "dreamplace/Placer.py", line 68, in place
>     placedb.read_pl(dp_out_file+".ntup.pl")
> AttributeError: 'PlaceDB' object has no attribute 'read_pl'
> ```

Hi, the latest commit [9d94df8](https://github.com/limbo018/DREAMPlace/commit/9d94df827714356d6d0e98a1c58180881ef66a89) has fixed this issue. You can check it out on master branch. 

Thanks
