### ISSUE TITLE
ModuleNotFoundError: No module named 'dreamplace.configure'

### ISSUE THREAD

**Issue by zhangbodaima** [limbo018/DREAMPlace#92]
I built the environment with docker and when I run  "python dreamplace/Placer.py test/ispd2005/adaptec1.json"
I got the following error:
File "dreamplace/Placer.py", line 19, in <module>
    import dreamplace.configure as configure
ModuleNotFoundError: No module named 'dreamplace.configure'

**Comment by limbo018** [comment]
You need to run from the installation path, not the repo path.
