### ISSUE TITLE
The parameter "target_density" in test/dac2012/*.json

### ISSUE THREAD

**Issue by YihangQiu** [limbo018/DREAMPlace#95]
Hi !
I found that the parameter "target_density" is equal to "0.9" in all dac2012/*.json.
![image](https://user-images.githubusercontent.com/65992277/198877949-2e361cc4-f956-4c8c-9f3f-1cb31d3de137.png)

But in DAC 2012 Benchmarksuit, it is recommended to set a specific value.
![image](https://user-images.githubusercontent.com/65992277/198877996-9ad54006-9745-4c3b-9b37-4660e64f1457.png)

So, **my question is, for the "target_density" parameter, do I keep the default parameter, or do I need to keep it consistent with the dac2012 dataset?**  Specifically, for superblue19, I set this parameter to 0.78 instead of the default 0.9?

Thanks for your reply !

**Comment by limbo018** [comment]
Hi, target density is a user-specific parameter and you can set it according to your needs. I checked old logs and notice that our previous results were collected with target_density = 0.9.

**Comment by YihangQiu** [comment]
Thanks! 
I have another question, that is, I tested the DAC2012 dataset using the default parameters you provided in json, but the results came out to be quite different from the results in your paper. 

I don't quite understand where the problem might be. Thanks for your reply!

1. dac2012/superblue2.json
![image](https://user-images.githubusercontent.com/65992277/198880214-59344b6f-8eaa-4525-807a-c89eec17f62d.png)
2. my results evaluated by dac2012_evaluate_solution.pl
![image](https://user-images.githubusercontent.com/65992277/198880232-0a0788a9-40bf-4aa2-b1b6-7512c54cd48d.png)
3. your results
![image](https://user-images.githubusercontent.com/65992277/198880308-a52ea61c-1f1a-4634-ac31-c43a8b34853c.png)

**Comment by YihangQiu** [comment]
In addition, when I execute the program 2 times for the same input, there is randomness in the results. This randomness is not good for my algorithm comparison. **Could you tell me how I can eliminate this randomness?** Thank you for your reply!

**Comment by limbo018** [comment]
Hi, I attached the old log for superblue2. One difference I notice is the detailed placement. We used ntuplace4h for detailed placement.

**Comment by limbo018** [comment]
> In addition, when I execute the program 2 times for the same input, there is randomness in the results. This randomness is not good for my algorithm comparison. **Could you tell me how I can eliminate this randomness?** Thank you for your reply!

You can turn on the deterministic_flag in JSON, which can help alleviate the problem. The randomness comes from atomicAdd in CUDA, which can cause numerical indeterminism. If I remember correctly, the latest code used atomicAdd in the ops related to the electric force computation for efficiency, which may lose determinism. Setting ```deterministic_flag``` does not completely disable this in the latest release, which needs to be fixed later.

**Comment by YihangQiu** [comment]
Thank you so much! 
Regarding the setting of num_bins, the result reported by the program does not match the json, which may be a bug. 
![image](https://user-images.githubusercontent.com/65992277/198882083-3cf6f366-5453-4eb1-9d2f-cdd48c855482.png)

**Comment by YihangQiu** [comment]
Thank you so much! I have no more questions and this issue can be closed.
